steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER##mu-}/mu-${CI_REPO_NAME}"
      tags: ${CI_COMMIT_BRANCH/\//-}
      platforms: linux/amd64,linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  branch: feature/*
  event: push
